services:
  - type: web
    name: gios-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GIOS_CORS_ORIGINS
        value: "*"
      - key: GIOS_DEBUG
        value: "false"
